# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Team
  description: Team section
  tags: ["block", "team"]

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  content:
  width: 504
  height: 504
  leftProfile:
    name:
    position:
    content:
    imagePath:
  rightProfile:
    name:
    position:
    content:
    imagePath:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  width:
    type: number
  height:
    type: number
